name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          # AGAR TUMAHA CODE KISI FOLDER KE ANDAR HAI TOH NICHE WALI LINE KA '#' HATAO AUR FOLDER KA NAAM LIKHO
          # cd TERE_FOLDER_KA_NAAM 
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/build/outputs/apk/debug/*.apk"
